#!/bin/sh

commit_msg_file=$1

# read commit title
commit_msg=$(head -n 1 "$commit_msg_file")

# reject if the commit title exceeds 50 characters
if [ ${#commit_msg} -gt 50 ]; then
  echo "Commit title must not exceed 50 characters. Current length: ${#commit_msg} characters"
  exit 1
fi

regex="^(feat|fix|doc|rename|remove|style|refactor|test|opt|script): [a-z][-_a-z0-9]*: [A-Z][-A-Za-z0-9_ ]*$"

if ! echo "$commit_msg" | grep -Eq "$regex"; then
  echo "Commit title rule error."
  exit 1
fi


#return success
exit 0